name: Hello
on: workflow_dispatch
jobs:
  hello:
   runs-on: ubuntu-latest
   steps:
     - name: hello sushmitha
       run: | 
        echo "hello github action" 
        echo "hello sushmitha goud" 
