name: Hello
on: push
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: hello sushmitha
       run: echo "hello build"         
  test:
   runs-on: ubuntu-latest
   steps:
     - name: hello sushmitha
       run: echo "hello test"
  deploy:
   runs-on: ubuntu-latest
   steps:
     - name: hello sushmitha
       run: echo "deploy" 